### PR TITLE
fix: useLayoutEffect should return nothing

### PR DESCRIPTION
**Pull request by cbbfcd**
for [#136](https://github.com/molefrog/wouter/issues/136)

### CODE REVIEW

**Comment by omgovich** [comment]
Nice catch!

**Comment by molefrog** [comment]
Great! @cbbfcd If possible, can you also write a simple spec that tests that the problem described in the issue has been fixed?
Steps to reproduce:
1. Write a custom hook that when `setLocation('/any')` is called returns a non-function (for example, "foo").
2. Provide the hook to `Router`, place a `Redirect` component.

With your fix, the spec should go green, and fail without. Thanks!

**Comment by cbbfcd** [comment]
@molefrog 👌

**Review by molefrog — APPROVED** [review]
Looks great!

**Pull request merged**
