### PR TITLE
Use effect should only ever return a function

### PR DESCRIPTION
**Pull request by timmak**
Currently use effect return the result of `push()` return the length of the array this will cause an warning inside of react.

### CODE REVIEW

**Comment by molefrog** [comment]
@timmak Good one, thanks! We should also probably add an empty array as a second argument to make sure redirect is only fired on component mount. Can you take care of that?

Also, can you run Prettier over modified files, think there is a semicolon missing.

**Comment by timmak** [comment]
Should be good now

**Comment by molefrog** [comment]
@timmak How soon do you need this to be published? I'm planning to implement a few other features before creating a release.

**Comment by timmak** [comment]
Can wait will just point to commit for now, as it not going to production anytime soon.

**Comment by molefrog** [comment]
@timmak Noted! Thanks for the PR.

**Pull request merged**
