### PR TITLE
Extends props interface for component Link

### PR DESCRIPTION
**Pull request by polRk**

### CODE REVIEW

**Comment by polRk** [comment]
Or is it better to expand component types with types React.AnchorHTMLAttributes<HTMLAnchorElement> ?

**Comment by Ty3uK** [comment]
@ you can check discussion at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37008

**Comment by molefrog** [comment]
> Or is it better to expand component types with types React.AnchorHTMLAttributes
Yes, that's probably better. Can we somehow tell that the component could accept all attributes from `React.AnchorHTMLAttributes` **and** also wouter-related props?

In the meantime, while types are not fixed yet you could try this workaround, which is actually a preferred way to use link in Wouter (the approach is similar to [using links in Next.js](https://nextjs.org/docs#with-link))
```js
<Link to="/app">
  <a className="link__container"> ... </a>
</Link>
```

**Comment by molefrog** [comment]
Hey @polRk, take a look at this PR #64
I've added a few tweaks to our typings and added type specs to better ensure that they indeed work. If this looks ok, we can merge the PR and release the new version with types bundled.

**Pull request closed without merging**
