### PR TITLE
Add useParams hook

### PR DESCRIPTION
**Pull request by Vija02**
This PR adds support for a `useParams` hook, briefly discussed in #161 and #245.
The main benefit is to allow users to access this data in any child component without having to pass the data all the way down. This makes creating more generic components tidier.

### Example
```js
import { Route, useParams } from "wouter";

const User = () => {
  // This can be called anywhere within the Route component
  const params = useParams();

  console.log(params.id)
};

<Route path="/user/:id" component={User}> />
```

### How does this work?
We wrap the user's component with a context provider. The `useParams` function in a simple wrapper for `useContext`.

### More info
The full changes itself are just a few lines in `index.js` ~and a new file `use-params.js`.~

This can be further minimized if needed but I think that'll make it much less readable.

Checking the size using `yarn size` shows that `index.js` grew from `1.05 kB` -> `1.06kB`.

I've done my best to add tests & documentation but they're pretty basic so please feel free to make changes or add more of them. Also, I'm not sure how the types work in this project so I tried matching existing ones but please do check them. Thanks!

### CODE REVIEW

**Review by molefrog — CHANGES_REQUESTED** [review]
Hi, thank you for working on adding this. The only thing I would change is I would move use-params.js inside of the main module. This method can't be used independently from the rest of the library, so there is no need to have an extra entry point.

**Comment by Vija02** [comment]
Thanks for having a look @molefrog! I've added a commit to move everything in `use-params.js` into `index.js` as you suggested.

**Comment by dominiceden** [comment]
Thanks @Vija02 - just wanted to say that this was the biggest thing I was missing vs React Router so looking forward to this! Thanks @molefrog for the great work on this lib too.

**Review by molefrog — APPROVED** [review]

**Comment by molefrog** [comment]
@Vija02 I have published wouter@2.12.0-beta.1 
There are some other features that I am considering for the next release, but you can use this version in the meantime.

**Pull request merged**
